var anObject = new Object();
console.log('value of an anObject:', anObject);
console.log('typeof anObject:', typeof anObject);
var anArray = new Array();
console.log('value of anArray:', anArray);
console.log('typeof anArray:', typeof anArray);
var anFunction = new Function();
console.log('value of anFunction:', anFunction);
console.log('typeof anFunction:', typeof anFunction);
var anString = new String();
console.log('value of anString:', anString);
console.log('typeof anString:', typeof anString);
var anNumber = new Number();
console.log('value of anNumber:', anNumber);
console.log('typeof anNumber:', typeof anNumber);
var anBoolean = new Boolean();
console.log('value of anBoolean:', anBoolean);
console.log('typeof Boolean:', typeof anBoolean);
